name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
    generate:
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run generate -- --force-build
